name: my_app
description: A new Flutter project with Diwali animations and sound effects.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # WebView Packages
  flutter_inappwebview: ^6.1.5  
  webview_flutter: ^4.7.0       
  webview_flutter_android: ^4.3.4
  webview_flutter_wkwebview: ^3.10.0
  webview_flutter_web: ^0.2.2+4

  # Sound and Animations
  audioplayers: ^6.0.0   # Ensure you use this version for stable sound
  flutter_animate: ^4.5.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/diwali_offer.html
    

# Override dependencies to avoid conflicts
dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  vm_service: ^15.0.0
  material_color_utilities: ^0.12.0

